### ISSUE TITLE
Compatibility reste sur False

### ISSUE THREAD

**Issue by bghilardibm** [laurentpertois/Monterey-Compatibility-Checker#4]
Bonjour,
je viens de mettre en place l'attribut d'extension pour essayer de gérer le déploiement de MacOS Monterey.
Je remarque que l'attribut reste sur False alors que je suis sur un MAcBookPro 13" M1 que j'ai bien 8Go et 110Go de libre sur le disque.
Je ne comprends pas pourquoi Compatibility ne passe pas sur true.
Une idée ?

**Comment by laurentpertois** [comment]
Bonjour,

Est-ce que ce MacBook Pro est déjà en Monterey ? Dans ce cas la réponse est false car au final l'utilité de l'attribut d'extension est de déterminer si un poste est compatible et a besoin de Monterey. Si vous souhaitez changer ce comportement, ligne 108 remplacez le 20 par un 21.

Cordialement

**Comment by bghilardibm** [comment]
Ok merci pour la réponse rapide.


Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Laurent Pertois ***@***.***>
Envoyé : Friday, June 3, 2022 12:03:39 PM
À : laurentpertois/Monterey-Compatibility-Checker ***@***.***>
Cc : GHILARDI Bruno ***@***.***>; Author ***@***.***>
Objet : Re: [laurentpertois/Monterey-Compatibility-Checker] Compatibility reste sur False (Issue #4)


⚠ Courriel d'un expéditeur externe


Bonjour,

Est-ce que ce MacBook Pro est déjà en Monterey ? Dans ce cas la réponse est false car au final l'utilité de l'attribut d'extension est de déterminer si un poste est compatible et a besoin de Monterey. Si vous souhaitez changer ce comportement, ligne 108 remplacez le 20 par un 21.

Cordialement
